# Ansible Playbook for Subutai Jitsi Blueprint
--- 

- hosts: meet
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name:
          - dirmngr
          - ca-certificates
          - apt-transport-https
          - sudo
          - locales
          - debconf
          - debconf-utils
        allow_unauthenticated: yes

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    # -------------------------------------------------------------------------
    # Install Jitsi Components
    # -------------------------------------------------------------------------

    - name: Install repository keys for Jitsi
      apt_key: 
        url: https://download.jitsi.org/jitsi-key.gpg.key
        state: present
    
    - name: Add binary repository repo
      apt_repository:
        repo: deb https://download.jitsi.org stable/
        update_cache: true
        state: present
    
    - name: Set jitsi-videobridge/jvb-hostname debconf variable for hostname
      debconf:
        name: jitsi-videobridge
        question: jitsi-videobridge/jvb-hostname
        vtype: string
        value: '{{ subutai.user_variables.domain }}'

    - name: Set jitsi-meet/cert-choice debconf variable for certificate
      debconf:
        name: jitsi-meet
        question: jitsi-meet/cert-choice 
        vtype: select
        value: 'Self-signed certificate will be generated'

    - name: Install required debs
      apt:
        name:
          - jitsi-meet   
